# output=<not set>
font=Lucida Grande:size=14
# dpi-aware=auto
use-bold=yes
prompt="% "
# icon-theme=hicolor
# icons-enabled=yes
# hide-before-typing=no
# fields=filename,name,generic
# password-character=*
# filter-desktop=no
# match-mode=fzf
match-counter=yes
show-actions=yes
# terminal=$TERMINAL -e  # Note: you cannot actually use environment variables here
# launch-prefix=<not set>
list-executables-in-path=yes

# anchor=center
# x-margin=0
# y-margin=0
# lines=15
# width=30
# tabs=8
# horizontal-pad=40
# vertical-pad=8
# inner-pad=0

# image-size-ratio=0.5

gamma-correct-blending=yes

# layer=overlay
keyboard-focus=on-demand
# exit-on-keyboard-focus-loss=yes

[colors]
background=f5f5f5ff
text=002b36ff
prompt=002b36ff
input=002b36ff
match=268bd2ff
selection=4271aeff
selection-text=f5f5f5ff
selection-match=d75f00ff
counter=586875ff
border=002b36ff

[border]
width=6
# radius=? # Note: this breaks niri's rounded corners
