# output=<not set>
font=Lucida Grande:size=14
# dpi-aware=auto
use-bold=yes
prompt="% "
# icon-theme=hicolor
# icons-enabled=yes
# hide-before-typing=no
# fields=filename,name,generic
# password-character=*
# filter-desktop=no
# match-mode=fzf
match-counter=yes
show-actions=yes
# terminal=$TERMINAL -e  # Note: you cannot actually use environment variables here
# launch-prefix=<not set>
list-executables-in-path=yes

# anchor=center
# x-margin=0
# y-margin=0
# lines=15
# width=30
# tabs=8
# horizontal-pad=40
# vertical-pad=8
# inner-pad=0

# image-size-ratio=0.5

# gamma-correct-blending=yes

# layer=overlay
keyboard-focus=on-demand
# exit-on-keyboard-focus-loss=yes

[colors]
background=ffffffff
text=000000ff
prompt=999999ff
input=000000ff
match=999999ff
selection=efefefff
selection-text=999999ff
selection-match=000000ff
counter=999999ff
border=000000ff

[border]
width=6
radius=0
