font=monospace:size=12
dpi-aware=yes
use-bold=yes
# message=
# message-mode=wrap 
prompt=": "
placeholder=The man page says "don't do that".
# icon-theme=hicolor
# icons-enabled=yes
# hide-before-typing=no
# fields=filename,name,generic
# password-character=*
# filter-desktop=no
match-mode=fuzzy
# sort-result=yes
show-actions=yes
terminal=foot -e
# launch-prefix=<not set>
# list-executables-in-path=no

# x-margin=0
# y-margin=0
lines=5
# minimal-lines=no 
width=40
# tabs=8
# horizontal-pad=40
# vertical-pad=8
# inner-pad=0

scaling-filter=cubic 

gamma-correct-blending=yes
line-height=22

# keyboard-focus=on-demand
# Setting this to false can be useful on compositors where enabling
# "focus-follows-mouse" causes fuzzel to exit as soon as the mouse
# is moved over another window. Sway (<= 1.7) exhibits this
# behavior, for example.
# Default: yes
# exit-on-keyboard-focus-loss=no

# auto-select=no
 								
[colors]
background=ffffffff
text=000000ff
prompt=000000ff
input=000000ff
match=999999ff
selection=efefefff
selection-text=999999ff
selection-match=000000ff
counter=999999ff
border=0c0a0eff

[border]
width=6
radius=0
selection-radius=0
