# Change the prefix key to C-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -s set-clipboard on
set -g allow-passthrough on
set -sa terminal-features "*:RGB"
set -g mouse on
set -g set-titles on
set -g status-bg blue
set -g status-fg cyan
set -g status-position top
set -g renumber-windows on

unbind s
unbind l
unbind x
unbind '"'
unbind %

bind a send-prefix
bind R source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; \
    display-message "source-file done"
bind S splitw -v -c '#{pane_current_path}'
bind s splitw -h -c '#{pane_current_path}'
bind Tab selectp -t :.+
bind X confirm-before killp
bind k confirm-before killw
bind Q killp -a
bind '"' command-prompt "find-window -NT '%%'"

bind ^a last-window
bind ^k confirm-before killw

# Status stuff.
set -g status-left-style fg=white,bg='#808080'
set -g status-left-length 30
set -g status-left "[#{session_name}]"
set -g status-right-length 30
set -g status-right-style fg=white,bg=blue
set -g status-right "#{?client_prefix,#[reverse][^a]#[noreverse],}#[bg=#A57922][%a-%m-%d %H:%M]"
set -g display-panes-active-colour red
set -g display-panes-colour green
set -g display-panes-time 4000

set -gw mode-style bg=blue,fg=yellow
set -gw mode-keys vi

set -g window-status-separator "| "
set -g window-status-format "#[fg=#{?window_bell_flag,black,default},bg=#{?window_bell_flag,'#F03B3B',default}]#I:#W:#{window_flags}"
set -g window-status-current-format "#[fg=black,bg=green]#I:#W:#{window_flags}"
set -gw clock-mode-colour green

# 9 man plumber
# See: https://9fans.github.io/plan9port/man/man4/plumber.html
bind -Tcopy-mode-vi Enter run "$HOME/bin/aplomb" \; send-keys -X cancel
bind -Tcopy-mode-vi M-Enter run "$HOME/bin/aplomb"

# See: https://github.com/helix-editor/helix/wiki/Terminal-Support#terminal-features
#
# Excerpt from BurntSushi:
# This is apparently necessary for a terminal's "focus" events to get passed
# through. This is required, for example, for neovim's `FocusGained` event to
# fire. And that is in turn necessary for my file auto-reloading hack to work
# like you'd expect.
#
# See: https://github.com/alacritty/alacritty/issues/572
set -g focus-events on

# Sessions
new -d -swork -d -nmail 'exec aerc'
neww -d -nirc 'exec senpai'
neww -d
neww -d
neww -d

new -d -sother -d
linkw -swork:irc -tother:1
swapw -sother:1 -tother:0
