# Colors hurt my eyes
set -g status-bg black
set -g status-fg white

set -g set-titles on

set -g status-position top

# Automatically renumber windows when one is killed
set -g renumber-windows on

# RBG is not needed on ghostty (i only tested on macos) but necessary for foot
set -sa terminal-features "*:RGB"

# Change the prefix key to C-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix
bind C-a last-window
bind a send-prefix

unbind s
unbind '"'
unbind %
bind S split-window -v
bind s split-window -h
bind '"' choose-window

# XXX: needs improvement
set-option -g mode-keys vi

# Send to the plumber(4)
bind -Tcopy-mode-vi Enter run "$HOME/bin/aplomb" \; send-keys -X cancel
bind -Tcopy-mode-vi M-Enter run "$HOME/bin/aplomb"

# Turn the mouse on
# https://doc.cat-v.org/plan_9/4th_edition/papers/acme/
set -g mouse on

# https://github.com/helix-editor/helix/wiki/Terminal-Support#terminal-features
#
# Excerpt from BurntSushi:
# This is apparently necessary for a terminal's "focus" events to get passed
# through. This is required, for example, for neovim's `FocusGained` event to
# fire. And that is in turn necessary for my file auto-reloading hack to work
# like you'd expect.
#
# See: https://github.com/alacritty/alacritty/issues/572
set -g focus-events on
