# ghostty (i only tested on macos) didn't need this but foot does?
set -sa terminal-features "*:RGB"

set -g prefix C-a
unbind C-b
bind C-a send-prefix

unbind s
unbind '"'
unbind %
bind S split-window -v
bind s split-window -h

bind C-a last-window

set -g mouse on

# https://github.com/helix-editor/helix/wiki/Terminal-Support#terminal-features
#
# excerpt from BurntSushi:
# This is apparently necessary for a terminal's "focus" events to get passed
# through. This is required, for example, for neovim's `FocusGained` event to
# fire. And that is in turn necessary for my file auto-reloading hack to work
# like you'd expect.
#
# See: https://github.com/alacritty/alacritty/issues/572
set -g focus-events on
