evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

colorscheme zenburn

define-command -hidden -params 1 user-colorcolumn %{
    add-highlighter -override window/user-colorcolumn column %arg{1} default,rgb:303030
}

# markdown files get hard tabs, wrapped at 79 and spell checking
hook global WinSetOption filetype=markdown %{
    set-option buffer autowrap_column 79
    set-option buffer indentwidth 0
    try %{ autowrap-enable }
    try %{ spell }
    user-colorcolumn 81
}

