evaluate-commands %sh{
    bundle="$kak_config/bundle"
    mkdir -p "$bundle"
    [ ! -e "$bundle/kak-bundle" ] && \
        git clone -q https://codeberg.org/jdugan6240/kak-bundle.git "$bundle/kak-bundle"
    printf "%s\n" "source '$bundle/kak-bundle/rc/kak-bundle.kak'"
}
bundle-noload kak-bundle https://codeberg.org/jdugan6240/kak-bundle

define-command load -params 2 %{
    source "%val{config}/%arg{1}/%arg{2}.kak"
}

colorscheme default

set global autoinfo ""
set global ui_options terminal_assistant=off
set global ui_options terminal_set_title=false
set global disabled_hooks '.+-highlight'

# Switch cursor color in insert mode
set-face global InsertCursor default,green+B

hook global ModeChange .*:.*:insert %{
    set-face window PrimaryCursor InsertCursor
    set-face window PrimaryCursorEol InsertCursor
}

hook global ModeChange .*:insert:.* %{ try %{
    unset-face window PrimaryCursor
    unset-face window PrimaryCursorEol
} }
