"attribute" = { fg = "#393939", modifiers = ["italic"] }
"keyword" = "#575757"
# "keyword.control" = "grey2" # for, if, while
"keyword.operator" = "#393939"
"keyword.directive" = "#575757"
"keyword.storage" = "grey1" # static (c)
"namespace" = { fg = "#0d0b07" }
"punctuation" = "#0d0b07"
"punctuation.delimiter" = "#393939" # pointer (c)
"punctuation.bracket" = "#939f91" # [[
"punctuation.special" = { fg = "fg", modifiers = ["italic"] } # $1, $HOME, the 'dollar sign'
"operator" = "#393939" # ==
"special" = "blue"
"variable" = "#000000"
"variable.builtin" = "DBlack" # LANG (sh)
"variable.parameter" = "#0d0b07"
"variable.other.member" = "#575757"
"type" = { fg = "#0d0b07", modifiers = ["italic"] } # void (c)
"constructor" = "green"
"function" = { fg = "#000000", modifiers = ["bold"] }
"function.macro" = "green"
"tag" = "orange"
"comment" = "#909090"
"constant" = "fg"
"constant.builtin" = "#393939"
"constant.builtin.boolean" = "#0d0b07"
"constant.numeric" = "#393939"
"constant.character.escape" = "green"
"string" = "grey2" # include "grey2" (c)
"string.regexp" = "DDarkgreen"
"string.special" = "#393939"
# used for lifetimes
"label" = "#0d0b07"

"markup.heading.marker" = "grey1"
"markup.list" = "red"
"markup.bold" = { fg = "#000000", modifiers = ["bold"] }
"markup.italic" = { fg = "#0d0b07", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "#44aa99", underline = { style = "line" } }
"markup.link.label" = "orange"
"markup.link.text" = "purple"
"markup.quote" = "grey1"
"markup.raw.inline" = "green"
"markup.raw.block" = "aqua"

"diff.plus" = { fg = "grey2", modifiers = ["bold"] }
"diff.minus" = "grey1"
"diff.delta" = { fg = "fg", modifiers = ["bold"] } # branch name in commit

# TODO: differentiate doc comment
# concat (ERROR) @error.syntax and "MISSING ;" selectors for errors

# "ui.background" = { bg = "#ffffff" }
"ui.background.separator" = "#939f91"
"ui.linenr" = "#939f91"
"ui.linenr.selected" = "grey2"
"ui.statusline" = { fg = "#887777", bg = "#f6f9e1" }
# "ui.statusline.inactive" = { fg = "#ff00dd", bg = "bg1" }
"ui.statusline.normal" = { fg = "DBlack", bg = "#f6f9e1", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "DBlack", bg = "#c6c6c6", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "DBlack", bg = "#72dec2", modifiers = ["bold"] }
"ui.popup" = { fg = "DBlack", bg = "#eaebd2" }
"ui.picker.header" = { modifiers = ["bold", "underlined"] }
"ui.window" = { fg = "bg4", bg = "purple" }
"ui.help" = { fg = "DBlack", bg = "DWhite" }
"ui.text" = { fg = "DBlack" }
"ui.text.focus" = "fg"
"ui.text.directory" = { fg = "#887777" }
"ui.virtual.ruler" = { bg = "#f6f9e1" }
"ui.virtual.whitespace" = { fg = "bg4" }
"ui.virtual.inlay-hint" = { fg = "#939f91" }
"ui.virtual.wrap" = { fg = "#939f91" }

"ui.virtual.indent-guide" = { fg = "bg4" }

"ui.selection" = { fg = "DBlack", bg = "#72dec2" }
# TODO: namespace ui.cursor as ui.selection.cursor?
"ui.cursor.select" = { bg = "DBlack" }
"ui.cursor.insert" = { bg = "DBlack" }
"ui.cursor.primary.select" = { fg = "DBlack", bg = "#f4f4f4" }
"ui.cursor.primary.insert" = { fg = "DBlack", bg = "#c6c6c6" }
"ui.cursor.match" = { bg = "DBlack", modifiers = ["bold"] }
"ui.cursor" = { fg = "#ffffea", bg = "DBlack" }
"ui.cursorline.primary" = { bg = "#f6f9e1" }
"ui.menu" = { fg = "DBlack", bg = "#d8d9c0" }
"ui.menu.selected" = { fg = "DBlack", bg = "#72dec2" }

"diagnostic.hint" = { underline = { color = "green", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"warning" = "yellow"
"error" = "red"
"info" = { fg = "DBlack", bg = "#58bcae", modifiers = ["bold"] }
"hint" = "green"

[palette]
bg4 = "#d8d3ba"

DBlack = "#000000"
DWhite = "#ffffff"
DDarkgreen = "#5f8700"

fg = "#5c6a72"
red = "#f85552"
orange = "#f57d26"
yellow = "#dfa000"
green = "#8da101"
blue = "#3a94c5"
aqua = "#35a77c"
purple = "#df69ba"

grey1 = "#829181"
grey2 = "#5c6a72"
