inherits = "rose_pine_dawn"

"attribute" = { fg = "ox_fg" }
"type" = { fg = "ox_fg", modifiers = ["italic"] }
"type.builtin" = { fg = "ox_fg", modifiers = ["italic"] }
"type.parameter" = { fg = "ox_fg", modifiers = ["italic"] }
"type.enum" = { fg = "ox_gray_2" }
"constructor" = { fg = "ox_entity" }
"constant" = { fg = "ox_gray_1" }
"constant.builtin" = { fg = "ox_gray_1" }
"constant.builtin.boolean" = { fg = "ox_fg" }
"constant.character" = { fg = "ox_gray_1" }
"constant.character.escape" = { fg = "ox_gray_2" }
"constant.numeric" = { fg = "ox_gray_1" }
"string" = { fg = "ox_gray_2" }
"string.regexp" = { fg = "ox_gray_2" }
"string.special" = { fg = "ox_gray_2" }
"comment" = { fg = "ox_comment" }
"comment.unused" = { fg = "ox_subtle", modifiers = ["dim"] }
"variable" = { fg = "ox_black" }
"variable.builtin" = { fg = "ox_gray_2" }
"variable.parameter" = { fg = "ox_fg" }
"variable.other.member" = { fg = "ox_gray_2" }
"label" = { fg = "ox_black" }
"punctuation" = { fg = "ox_fg" }
"punctuation.delimiter" = { fg = "ox_gray_1" }
"punctuation.bracket" = { fg = "ox_fg" }
"punctuation.special" = { fg = "ox_gray_2" }
"keyword" = { fg = "ox_gray_2" }
"keyword.control" = { fg = "ox_gray_2" }
"keyword.control.import" = { fg = "ox_fg" }
"keyword.operator" = { fg = "ox_gray_1" }
"keyword.directive" = { fg = "ox_gray_2" }
"keyword.function" = { fg = "ox_gray_1" }
"keyword.storage" = { fg = "ox_fg", modifiers = ["italic"] }
"keyword.storage.type" = { fg = "ox_fg", modifiers = ["italic"] }
"keyword.storage.modifier" = { fg = "ox_gray_2" }
"operator" = { fg = "ox_gray_1" }
"function" = { fg = "ox_black", modifiers = ["bold"] }
"function.builtin" = { fg = "ox_gray_2" }
"function.method" = { fg = "ox_black", modifiers = ["bold"] }
"function.method.private" = { fg = "ox_gray_2", modifiers = ["bold"] }
"function.macro" = { fg = "ox_alert", modifiers = ["bold"] }
"function.special" = { fg = "ox_gray_2" }
"tag" = { fg = "ox_gray_2", modifiers = ["bold"] }
"namespace" = { fg = "ox_gray_2" }
"special" = { fg = "ox_gray_2" }
"markup.heading" = { fg = "ox_black", modifiers = ["bold"] }
"markup.heading.marker" = { fg = "ox_gray_2" }
"markup.list" = { fg = "ox_gray_2" }
"markup.bold" = { fg = "ox_black", modifiers = ["bold"] }
"markup.italic" = { fg = "ox_fg", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "ox_gray_2", underline = { style = "line" } }
"markup.link.text" = { fg = "ox_gray_2" }
"markup.link.label" = { fg = "ox_gray_2" }
"markup.quote" = { fg = "ox_gray_2", bg = "surface" }
"markup.raw" = { fg = "ox_black", bg = "surface", modifiers = ["bold"] }
"markup.raw.inline" = { fg = "ox_black", bg = "surface" }
"markup.raw.block" = { fg = "ox_black", bg = "surface" }
"diff.plus" = { fg = "ox_gray_2" }
"diff.delta" = { fg = "ox_gray_1" }
"diff.minus" = { fg = "ox_alert" }
"warning" = { fg = "ox_gray_2" }
"error" = { fg = "ox_alert" }
"info" = { fg = "ox_gray_2" }
"hint" = { fg = "ox_entity" }
"diagnostic" = { underline = { color = "ox_gray_2", style = "curl" } }
"diagnostic.warning" = { underline = { color = "ox_gray_2", style = "curl" } }
"diagnostic.error" = { underline = { color = "ox_alert", style = "curl" } }
"diagnostic.info" = { underline = { color = "ox_gray_2", style = "curl" } }
"diagnostic.hint" = { underline = { color = "ox_entity", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"ui.background" = { bg = "base" }
"ui.background.separator" = { fg = "highlight_high" }
"ui.text" = { fg = "ox_fg" }
"ui.text.focus" = { fg = "ox_black", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "ox_disabled" }
"ui.text.info" = { fg = "ox_gray_2" }
"ui.text.warning" = { fg = "ox_gray_2" }
"ui.text.error" = { fg = "ox_alert" }
"ui.text.directory" = { fg = "ox_black", modifiers = ["bold"] }
"ui.virtual" = { fg = "ox_subtle" }
"ui.virtual.ruler" = { bg = "highlight_low" }
"ui.virtual.whitespace" = { fg = "highlight_high" }
"ui.virtual.indent-guide" = { fg = "highlight_high" }
"ui.virtual.inlay-hint" = { fg = "ox_inlay", bg = "surface" }
"ui.virtual.wrap" = { fg = "ox_subtle" }
"ui.virtual.jump-label" = { fg = "ox_black", bg = "highlight_med", modifiers = ["bold"] }
"ui.cursor" = { fg = "base", bg = "ox_black" }
"ui.cursor.primary" = { fg = "base", bg = "ox_black" }
"ui.cursor.match" = { fg = "ox_black", bg = "highlight_med" }
"ui.cursor.normal" = { fg = "base", bg = "ox_black" }
"ui.cursor.insert" = { fg = "base", bg = "ox_black" }
"ui.cursor.select" = { fg = "base", bg = "ox_black" }
"ui.cursor.primary.normal" = { fg = "base", bg = "ox_black" }
"ui.cursor.primary.insert" = { fg = "base", bg = "ox_black" }
"ui.cursor.primary.select" = { fg = "base", bg = "ox_black" }
"ui.selection" = { fg = "ox_fg", bg = "highlight_med" }
"ui.selection.primary" = { fg = "ox_fg", bg = "highlight_med" }
"ui.highlight" = { bg = "highlight_low" }
"ui.highlight.frameline" = { bg = "surface" }
"ui.linenr" = { fg = "ox_subtle" }
"ui.linenr.selected" = { fg = "ox_entity" }
"ui.statusline" = { fg = "ox_entity", bg = "base" }
"ui.statusline.inactive" = { fg = "ox_disabled", bg = "surface" }
"ui.statusline.normal" = { fg = "ox_black", bg = "highlight_med", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "ox_black", bg = "highlight_med", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "ox_black", bg = "highlight_med", modifiers = ["bold"] }
"ui.statusline.separator" = { fg = "highlight_high" }
"ui.bufferline" = { fg = "ox_disabled", bg = "base" }
"ui.bufferline.active" = { fg = "ox_black", bg = "base", modifiers = ["bold"] }
"ui.bufferline.background" = { bg = "base" }
"ui.popup" = { fg = "ox_entity", bg = "surface" }
"ui.popup.info" = { fg = "ox_entity", bg = "surface" }
"ui.window" = { fg = "highlight_high" }
"ui.help" = { fg = "ox_entity", bg = "surface" }
"ui.menu" = { fg = "ox_entity", bg = "surface" }
"ui.menu.selected" = { fg = "ox_black", bg = "highlight_med", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "ox_subtle", bg = "surface" }
"ui.picker.header" = { fg = "ox_black", modifiers = ["bold"] }
"ui.picker.header.column" = { fg = "ox_fg" }
"ui.picker.header.column.active" = { fg = "ox_black", modifiers = ["bold"] }
"ui.gutter" = { bg = "base" }
"ui.gutter.selected" = { bg = "base" }
"ui.cursorline" = { bg = "highlight_low" }
"ui.cursorline.primary" = { bg = "highlight_low" }
"ui.cursorline.secondary" = { bg = "highlight_low" }
"ui.cursorcolumn.primary" = { bg = "highlight_low" }
"ui.cursorcolumn.secondary" = { bg = "highlight_low" }
"ui.debug.breakpoint" = { fg = "ox_alert" }
"ui.debug.active" = { fg = "ox_black", bg = "highlight_med" }
"ui.gutter.debug" = { fg = "ox_alert" }
"ui.gutter.diff.added" = { fg = "ox_gray_2" }
"ui.gutter.diff.modified" = { fg = "ox_gray_2" }
"ui.gutter.diff.removed" = { fg = "ox_alert" }
"tabstop" = { fg = "ox_black", bg = "highlight_med" }
"markup.normal.completion" = { fg = "ox_entity", bg = "surface" }
"markup.heading.completion" = { fg = "ox_black", bg = "surface", modifiers = ["bold"] }
"markup.raw.inline.completion" = { fg = "ox_black", bg = "highlight_low" }
"markup.normal.hover" = { fg = "ox_entity", bg = "surface" }
"markup.heading.hover" = { fg = "ox_black", bg = "surface", modifiers = ["bold"] }
"markup.raw.inline.hover" = { fg = "ox_black", bg = "highlight_low" }

[palette]
ox_fg = "#0d0b07"
ox_entity = "#221e19"
ox_black = "#000000"
ox_gray_1 = "#393939"
ox_gray_2 = "#575757"
ox_alert = "#727272"
ox_comment = "#909090"
ox_subtle = "#c6c6c6"
ox_disabled = "#727272"
ox_inlay = "#525757"

