#!/bin/sh

if [ -x "`command -v vim`" ]; then
	alias vi="vim"
	alias view="vim -R"
fi

# muon/samu setup if available
if [ -x "`command -v muon`" ]; then
	alias msn="muon"
	alias samu="muon samu"
else
	alias msn="meson"
fi

# nice things to have
alias \
	acme="acme -a -f $font -F $font1"\
	cp="cp -i"\
	edwood="edwood -a -f $font -F $font1"\
	hg="chg"\
	lc="lc -F"\
	ll="ls -AlF"\
	ls="ls -AF"\
	ltr="ls -AlFtr"\
	m="make"\
	mv="mv -i"\
	ph="ps auwwx | head"\
	sam="sam -a"

# for use in 9term and acme's win
if [ "$termprog" ] || [ "$winid" ]; then
	_cd() {
		\cd "$@" && awd
	}
	awd
	alias \
		cd="_cd"\
		git="git --no-pager"\
		hg="chg --pager=no"\
		jj="jj --no-pager"
fi

if [ "`uname`" = "Darwin" ]; then
	alias rcctl="launchctl"
fi

if [ "`uname`" = "Linux" ]; then
	alias \
		ls="ls -AFv"\
		pQm="pacman -Qm"\
		ph="ps auwwx | sort -rk 3,3 | head"\
		rcctl="systemctl"
fi

if [ "`uname`" = "OpenBSD" ]; then
	# check shared libs version
	cshlib() {
		local cnt=0
		local f

		for f in `make show=SHARED_LIBS`; do
			[ "`(cnt++ % 2)`" -eq 1 ] && continue
			echo '===>' "$f"
			/usr/src/lib/check_sym /usr/local/lib/lib"$f".so* \
				"`make show=WRKINST`"/usr/local/lib/lib"$f".so*
		done
	}

	alias \
		cvs="opencvs"\
		mpldc="make port-lib-depends-check"\
		mup="make update-patches"\
		mupl="make update-plist"\
		pclean='make clean="package plist"'\
		rsync="openrsync"
fi

# making sure these are running
felloff() {
	mkdir -p $NAMESPACE
	9p stat plumb 2>/dev/null 1>&2 || plumber
}

if [ -d "$PLAN9" ]; then
	felloff
fi
