#!/bin/sh

# paths
OS=`uname | tr '[:upper:]' '[:lower:]'`
ARCH=`uname -m`
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin:/usr/local/sbin:/usr/local/bin
BIN=$HOME/bin:$HOME/bin/$OS:$HOME/bin/$OS/$ARCH
PLAN9=/usr/local/plan9
PATH=.:$BIN:$HOME/go/bin:$PATH:$PLAN9/bin

# personal variables
if [ -x "`command -v emacsclient`" ]; then
	EDITOR="emacsclient"
else
	EDITOR=/usr/bin/mg
fi
BASH_SILENCE_DEPRECATION_WARNING=1
BROWSER=firefox
CARGO_HOME=$HOME/.local/share/cargo
CUDA_CACHE_PATH=$HOME/.cache/nv
GOT_AUTHOR="demian garcia <d@sfyatee.com>"
GOTELEMETRY=off
GOTOOLCHAIN=local
GS_FONTPATH=$PLAN9/postscript/font
HISTFILE=/dev/null
HISTSIZE=500
LESS="-i"
LESSHISTFILE=/dev/null
NAMESPACE=/tmp/ns.$USER.:0
NO_COLOR=1
PYTHON_HISTORY=/dev/null
RUSTUP_HOME=$HOME/.local/share/rustup
XDG_CONFIG_HOME=$HOME/.config

# prepare path enviornment
PATH=$CARGO_HOME/bin:$PATH:$PLAN9/bin/upas

# plan9
font=/mnt/font/LucidaGrande/11a/font
font1=/mnt/font/Hack-Regular/11a/font
home=$HOME
secstore=localhost
user=$USER

# emulate rc shell
set -a	# autoexport
set +o vi	# turn it off

# for use in 9term and acme's win
if [ "$termprog" ] || [ "$winid" ]; then
	EDITOR=editinacme
	GH_PROMPT_DISABLED=1
	PAGER=nobs
fi

# os specific settings
if [ "$OS" = "darwin" ]; then
	PATH=/usr/local/go/bin:$PATH
	JJ_CONFIG=$HOME/.config/jj/config.toml
	font=/mnt/font/LucidaGrande/14a/font
	font1=/mnt/font/Hack-Regular/14a/font
fi

if [ "$OS" = "darwin" ] || [ "$OS" = "*bsd" ]; then
	NPROC=`sysctl -n hw.ncpu`
	stty status '^T'
fi

if [ "$OS" = "linux" ]; then
	NPROC=`nproc`
fi

# use $NPROC jobs
MAKEFLAGS=-j$NPROC

if [ "$OS" = "openbsd" ]; then
	export CDPATH=.:/usr/ports:/usr/ports/mystuff
fi

ulimit -c 0	# don't litter

export \
	ARCH\
	BASH_SILENCE_DEPRECATION_WARNING\
	BROWSER\
	CARGO_HOME\
	CUDA_CACHE_PATH\
	EDITOR\
	GH_PROMPT_DISABLED\
	GOT_AUTHOR\
	GOTELEMETRY\
	GOTOOLCHAIN\
	GS_FONTPATH\
	HISTSIZE\
	JJ_CONFIG\
	LESS\
	LESSHISTFILE\
	MAKEFLAGS\
	NAMESPACE\
	NO_COLOR\
	NPROC\
	OS\
	PAGER\
	PATH\
	PLAN9\
	PYTHON_HISTORY\
	RIPGREP_CONFIG_PATH\
	RUSTUP_HOME\
	W3M_DIR\
	XDG_CONFIG_HOME\
	font\
	font1\
	home\
	user\
	secstore\
