bar:
  height: 24
  location: top
  background: FFF8E1FF
  margin: 6
  border:
    width: 6
    color: 000000FF
  font: Microsoft Sans Serif:size=14:weight=bold
  foreground: 000000FF

  left:
    - niri-workspaces:
        content:
          map:
            default:
              string: {text: "| {id}"}
            conditions:
              active: {string: {text: "-> {id}"}}
              ~empty: {string: {text: "@ {id}"}}
  right:
    - clock:
        date-format: "%Y/%m/%d %a"
        content:
          - string: {text: "{date} {time}"}
