bar:
  height: 24
  location: bottom
  background: 000000ff
  margin: 14
  font: Lucida Grande:size=14:weight=bold
  foreground: ffffffff

  left:
    - niri-workspaces:
        content:
          map:
            default:
              string: {text: "| {id}"}
            conditions:
              active: {string: {text: "-> {id}"}}
              ~empty: {string: {text: "@ {id}"}}
  right:
    - clock:
        content:
          - string: {text: "{time}"}
