# -*- conf -*-
# Electrophoretic
# Theme for electrophoretic displays (like e-ink) which usually supports
# 16 levels of grays. This theme aims to maximize the contrast between the
# text and the white background.
# author: Eugen Rahaian <eugen@rah.ro>

[colors.primary]
background= '#ffffff'
foreground= '#000000'

# The colors are sorted based on their luminance, so we can more easily assign
# them a gray level.
# grayscale order: black_0 blue_4 red_1 magenta_5 green_2 cyan_6 yellow_3 white_7
[colors.normal]
black=	'#ffffff'
blue=	'#616161'
red=   '#515151'
magenta=   '#414141'
green=   '#313131'
cyan=   '#212121'
yellow=   '#111111'
white=   '#000000'
# Here, we also stay away from the white background by reusing the dark gray levels
# from above, with small variations
[colors.bright]
black=    '#818181'
blue=    '#717171'
red=    '#616161'
magenta=    '#515151'
green=    '#414141'
cyan=    '#313131'
yellow=    '#212121'
white=    '#111111'
