output current
desk current
page current
sort none
group-by none
match title=!stats
match title=!volume
show-self false
icons false
iconified-marker false
button-relief flat
button-width 200
frame-padding 5
style background 0xeaffff
style active.bg 0x9eeeee
style active.fg 0x000000
style inactive.bg 0xeaffff
style inactive.fg 0x000000
style iconified.bg 0xcccccc
style border 0x000000
