general.import = [
"~/.config/alacritty/themes/material-amber.toml"
]

[window]
padding = { x = 16, y = 16 }
dynamic_padding = true
decorations = "Buttonless"

[font]
normal = { family = "Space Mono" }
