theme = 'rose_pine_dawn'

[editor]
cursorline = true
gutters = []
color-modes = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "warning"
