# makefiles and c have tabstops at 8 for portability
[[language]]
name = "c"
indent = { tab-width = 8, unit = "" }
[[language]]
name = "make"
indent = { tab-width = 8, unit = "" }

# email and commit messages
[[language]]
name = "git-commit"
rulers = [69]
[[language]]
name = "mail"
rulers = [69]
