# all source code gets wrapped at <80 and auto-indented
[[language]]
name = "go"
soft-wrap = { enable = true, wrap-at-text-width = true }
text-width = 79
rulers = [81]
[[language]]
name = "rust"
soft-wrap = { enable = true, wrap-at-text-width = true }
text-width = 79
rulers = [81]
[[language]]
name = "java"
soft-wrap = { enable = true, wrap-at-text-width = true }
text-width = 79
rulers = [81]
[[language]]
name = "javascript"
soft-wrap = { enable = true, wrap-at-text-width = true }
text-width = 79
rulers = [81]
[[language]]
name = "java"
soft-wrap = { enable = true, wrap-at-text-width = true }
text-width = 79
rulers = [81]
[[language]]
name = "php"
soft-wrap = { enable = true, wrap-at-text-width = true }
text-width = 79
rulers = [81]
[[language]]
name = "html"
soft-wrap = { enable = true, wrap-at-text-width = true }
text-width = 79
rulers = [81]
[[language]]
name = "perl"
soft-wrap = { enable = true, wrap-at-text-width = true }
text-width = 79
rulers = [81]

# makefiles and c have tabstops at 8 for portability
[[language]]
name = "c"
indent = { tab-width = 8, unit = "" }
rulers = [81]
[[language]]
name = "gas"
indent = { tab-width = 8, unit = "" }
rulers = [81]
[[language]]
name = "make"
indent = { tab-width = 8, unit = "" }
rulers = [81]
[[language]]
name = "nasm"
indent = { tab-width = 8, unit = "" }
rulers = [81]
[[language]]
name = "bash"
indent = { tab-width = 8, unit = "" }
rulers = [81]

# email and commit messages - expand tabs, wrap at 68 for future quoting, enable spelling
[[language]]
name = "git-commit"
soft-wrap = { enable = true, wrap-at-text-width = true }
text-width = 68
rulers = [69]
[[language]]
name = "mail"
soft-wrap = { enable = true, wrap-at-text-width = true }
text-width = 68
rulers = [69]

# markdown files get hard tabs, wrapped at 79 and spell checking
[[language]]
name = "markdown"
soft-wrap = { enable = true, wrap-at-text-width = true }
text-width = 79
rulers = [81]
