# makefiles and c have tabstops at 8 for portability
[[language]]
name = "c"
indent = { tab-width = 8, unit = "" }
rulers = [81]
[[language]]
name = "gas"
indent = { tab-width = 8, unit = "" }
rulers = [81]
[[language]]
name = "make"
indent = { tab-width = 8, unit = "" }
rulers = [81]
[[language]]
name = "nasm"
indent = { tab-width = 8, unit = "" }
rulers = [81]
[[language]]
name = "bash"
indent = { tab-width = 8, unit = "" }
rulers = [81]

# email and commit messages
[[language]]
name = "git-commit"
rulers = [69]
[[language]]
name = "mail"
rulers = [69]

# markdown files get hard tabs, wrapped at 79 and spell checking
[[language]]
name = "markdown"
soft-wrap = { enable = true, wrap-at-text-width = true }
text-width = 79
rulers = [81]
