# Flat Redmond 98-style theme.

decor -d redmond98 border.width 5
decor -d redmond98 border.style fvwm
decor -d redmond98 border.corner_length 5
decor -d redmond98 border.handles false
decor -d redmond98 titlebar.enabled true
decor -d redmond98 titlebar.height 20
decor -d redmond98 titlebar.font 'Lucida Typewriter 12'

decor -d redmond98 border.active 0xC3C3C3
decor -d redmond98 border.inactive 0xC3C3C3
decor -d redmond98 border.active.image none
decor -d redmond98 border.inactive.image none
decor -d redmond98 border.active.gradient none
decor -d redmond98 border.inactive.gradient none

decor -d redmond98 titlebar.active_colour 0x00008B
decor -d redmond98 titlebar.inactive_colour 0x828282
decor -d redmond98 titlebar.fg_active 0xFFFFFF
decor -d redmond98 titlebar.fg_inactive 0xFFFFFF
decor -d redmond98 titlebar.active_image none
decor -d redmond98 titlebar.inactive_image none
decor -d redmond98 titlebar.active_gradient HGradient 0x00008B 0x00BFFF
decor -d redmond98 titlebar.inactive_gradient none

decor -d redmond98 titlebar.button.0.image svg/button-close.svg
decor -d redmond98 titlebar.button.0.action 'winops -c'
decor -d redmond98 titlebar.button.1.image svg/button-menu.svg
decor -d redmond98 titlebar.button.1.action ''
decor -d redmond98 titlebar.button.2.image svg/button-max.svg
decor -d redmond98 titlebar.button.2.action 'window-maximize -T'
decor -d redmond98 titlebar.button.4.image svg/button-min.svg
decor -d redmond98 titlebar.button.4.action 'winops -i'

decor -d redmond98 container.tab.active_colour 0x00008B
decor -d redmond98 container.tab.inactive_colour 0x828282
decor -d redmond98 container.tab.fg_active 0xFFFFFF
decor -d redmond98 container.tab.fg_inactive 0xFFFFFF
decor -d redmond98 container.tab.active_image none
decor -d redmond98 container.tab.inactive_image none
decor -d redmond98 container.tab.active_gradient HGradient 0x00008B 0x00BFFF
decor -d redmond98 container.tab.inactive_gradient none
